[package]
name = "lnx"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive", "wrap_help", "color"] }
hashbrown = "0.14.5"
scraper = "0.19.0"
thiserror = "1.0.62"
